apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongoexpress
  name: mongoexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongoexpress
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: mongoexpress
    spec:
      containers:
        - env:
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: securedpassword
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: securedpassword
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
          image: mongo-express
          name: mongoexpress
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
