apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vincent-ns
  name: vincent-ns-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","services","ingresses"]
  verbs: ["create","delete","deletecollection","get","list","patch","update","watch"]